feat(main.rs): append/use plugin name rather than package filename
itowlson/spin-pluginify pull request #7
Opened 2023-08-17 22:17 UTC by vdice

This allows for an arbitrary package/executable name but ensures the plugin is invoked by its assigned name via spin.

This won't change the behavior when the plugin name and package filename are the same, which might usually be the case, but supports use cases where the filename may differ per the plugin developer's use case.  For example a `foo` plugin whose package filename is `foo-plugin`:

```toml
name = "foo"
version = "0.1"
spin_compatibility = ">=0.7"
license = "Apache-2.0"
package = "./target/release/foo-plugin"
```

Regardless of the package filename, the plugin will be invoked via its given name, here `"foo"`, eg `spin foo bar`.

2023-08-17 22:37 UTC, itowlson requested changes
The same thing bit me on the butt all the damn time... _grin_

2023-08-17 22:37 UTC, itowlson commented on src/main.rs
> +            eprintln!("Appending {} with name {:?}", package.display(), ps.name);
This might need to be Windowsified I think?  (This wasn't an issue with `package.file_name` because a prior step Windowsified that already.)

2023-08-17 22:37 UTC, itowlson commented on src/main.rs
> +                tar_builder.append_path_with_name(&package, &ps.name)?;
Again I think we need to consider the Windows case?

2023-08-17 22:59 UTC, vdice commented
Thanks @itowlson; updated.  Also open to var name alternatives if `os_specific_name` is too wordy or otherwise insufficient.

2023-08-17 23:59 UTC, itowlson commented
Sorry @vdice, I wasn't clear - the worry is not about using an OS string - it is that on Windows, the name needs to have a `.exe` suffix.  We mangle the _source_ executable path at https://github.com/itowlson/spin-pluginify/blob/466d7e889a4828421ef12352ce455465933d39f0/src/main.rs#L257 - but with your change we no longer mangle the _tarred_ executable name.  Hope that makes more sense now.

2023-08-18 15:09 UTC, vdice commented
I see now (I hope), thank you.  Added a bit of code though eager for pointers on simplifying or a better way to do the job.

2023-08-20 21:28 UTC, itowlson approved these changes
LGTM - thanks!

2023-08-20 22:05 UTC, merged